# Generated by Django 6.0.7 on 2026-08-23 08:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم الدوري')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط حالياً')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم اللاعب')),
                ('position', models.CharField(choices=[('GK', 'حارس مرمى'), ('DEF', 'مدافع'), ('MID', 'وسط'), ('FWD', 'مهاجم')], max_length=3, verbose_name='المركز')),
                ('price', models.DecimalField(decimal_places=1, default=5.0, max_digits=4, verbose_name='السعر')),
            ],
        ),
        migrations.CreateModel(
            name='Gameweek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(verbose_name='رقم الجولة')),
                ('is_open', models.BooleanField(default=True, verbose_name='باب التغيير مفتوح')),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fantasy.league')),
            ],
        ),
        migrations.CreateModel(
            name='PlayerGameweekStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goals', models.PositiveIntegerField(default=0, verbose_name='الأهداف')),
                ('assists', models.PositiveIntegerField(default=0, verbose_name='الأسيست')),
                ('clean_sheet', models.BooleanField(default=False, verbose_name='كلين شيت')),
                ('yellow_cards', models.PositiveIntegerField(default=0, verbose_name='كروت صفراء')),
                ('red_cards', models.PositiveIntegerField(default=0, verbose_name='كروت حمراء')),
                ('points', models.IntegerField(default=0, verbose_name='النقاط')),
                ('gameweek', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fantasy.gameweek')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fantasy.player')),
            ],
        ),
        migrations.CreateModel(
            name='RealTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم الفريق')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='team_logos/', verbose_name='شعار الفريق')),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='fantasy.league')),
            ],
        ),
        migrations.AddField(
            model_name='player',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='fantasy.realteam'),
        ),
        migrations.CreateModel(
            name='UserFantasyTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم فرقتك')),
                ('budget', models.DecimalField(decimal_places=1, default=100.0, max_digits=5, verbose_name='الميزانية المتبقية')),
                ('total_points', models.IntegerField(default=0, verbose_name='إجمالي النقاط')),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fantasy.league')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserSquad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points_earned', models.IntegerField(default=0, verbose_name='نقاط الجولة')),
                ('captain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='captained_in', to='fantasy.player', verbose_name='الكابتن (x2)')),
                ('gameweek', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fantasy.gameweek')),
                ('starting_players', models.ManyToManyField(related_name='starters', to='fantasy.player', verbose_name='الأساسيين (6)')),
                ('substitutes', models.ManyToManyField(related_name='subs', to='fantasy.player', verbose_name='الاحتياط (4)')),
                ('user_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fantasy.userfantasyteam')),
            ],
        ),
    ]
