# Generated by Django 6.0.7 on 2026-08-23 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='position',
            field=models.CharField(choices=[('GK', 'حارس مرمى'), ('CB', 'قلب دفاع'), ('RB', 'ظهير أيمن (باك يمين)'), ('LB', 'ظهير أيسر (باك شمال)'), ('RWB', 'جناح دفاعي أيمن'), ('LWB', 'جناح دفاعي أيسر'), ('CDM', 'وسط مدافع (ديفندر)'), ('CM', 'وسط ملعب (ارتكاز)'), ('CAM', 'صانع ألعاب'), ('RM', 'وسط أيمن'), ('LM', 'وسط أيسر'), ('RW', 'جناح أيمن'), ('LW', 'جناح أيسر'), ('ST', 'مهاجم صريح (راس حرب)'), ('CF', 'مهاجم ثاني / وهمي')], max_length=5, verbose_name='المركز التفصيلي'),
        ),
    ]
