# Generated by Django 6.0.7 on 2026-08-23 11:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy', '0002_alter_player_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersquad',
            name='captain',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='captained_in', to='fantasy.player', verbose_name='الكابتن (x2)'),
        ),
    ]
