# Generated by Django 6.0.7 on 2026-08-25 07:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy', '0003_alter_usersquad_captain'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='code',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True, verbose_name='كود الانضمام الخاص'),
        ),
        migrations.AddField(
            model_name='league',
            name='is_public',
            field=models.BooleanField(default=True, verbose_name='بطولة عامة مفتوحة'),
        ),
        migrations.AlterField(
            model_name='league',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='نشطة حالياً'),
        ),
        migrations.AlterField(
            model_name='league',
            name='name',
            field=models.CharField(max_length=100, verbose_name='اسم البطولة'),
        ),
        migrations.AlterField(
            model_name='userfantasyteam',
            name='league',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_teams', to='fantasy.league'),
        ),
        migrations.AlterField(
            model_name='userfantasyteam',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fantasy_teams', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='usersquad',
            name='user_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='squads', to='fantasy.userfantasyteam'),
        ),
        migrations.AlterUniqueTogether(
            name='userfantasyteam',
            unique_together={('user', 'league')},
        ),
        migrations.AlterUniqueTogether(
            name='usersquad',
            unique_together={('user_team', 'gameweek')},
        ),
    ]
