# Generated by Django 6.0.7 on 2026-08-25 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy', '0005_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersquad',
            name='transfers_cost',
            field=models.IntegerField(default=0, verbose_name='خصم التغييرات'),
        ),
    ]
