# Generated by Django 6.0.7 on 2026-08-25 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy', '0006_usersquad_transfers_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='playergameweekstat',
            name='penalties_missed',
            field=models.PositiveIntegerField(default=0, verbose_name='ضربات الجزاء الضائعة'),
        ),
        migrations.AddField(
            model_name='playergameweekstat',
            name='penalties_taken',
            field=models.PositiveIntegerField(default=0, verbose_name='ضربات الجزاء المسددة'),
        ),
    ]
