# Generated by Django 6.0.7 on 2026-08-25 17:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy', '0007_playergameweekstat_penalties_missed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='is_suspended',
            field=models.BooleanField(default=False, verbose_name='معاقب/موقوف'),
        ),
        migrations.AddField(
            model_name='player',
            name='suspended_matches_left',
            field=models.PositiveIntegerField(default=0, verbose_name='المباريات المتبقية للإيقاف'),
        ),
        migrations.AddField(
            model_name='playergameweekstat',
            name='suspension_matches',
            field=models.PositiveIntegerField(default=0, verbose_name='عدد مباريات الإيقاف'),
        ),
        migrations.AddField(
            model_name='playergameweekstat',
            name='suspension_notes',
            field=models.TextField(blank=True, null=True, verbose_name='ملاحظات تفاصيل العقوبة'),
        ),
        migrations.AddField(
            model_name='playergameweekstat',
            name='suspension_reason',
            field=models.CharField(choices=[('NONE', 'لا يوجد'), ('RED_CARD', 'طرد مباشر / كروت'), ('DISCIPLINARY', 'عقوبة أخلاقية / سلوك'), ('CLUB_DECISION', 'قرار إداري / إيقاف نادٍ')], default='NONE', max_length=20, verbose_name='سبب العقوبة'),
        ),
        migrations.AlterField(
            model_name='playergameweekstat',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gameweek_stats', to='fantasy.player'),
        ),
    ]
