# Generated by Django 6.0.7 on 2026-08-28 08:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy', '0008_player_is_suspended_player_suspended_matches_left_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersquad',
            name='vice_captain',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vice_captained_in', to='fantasy.player', verbose_name='نائب الكابتن'),
        ),
    ]
