# Generated by Django 6.0.7 on 2026-08-28 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy', '0009_usersquad_vice_captain'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersquad',
            name='is_saved',
            field=models.BooleanField(default=False, verbose_name='تم حفظ التشكيلة'),
        ),
        migrations.AddField(
            model_name='usersquad',
            name='transfers_made',
            field=models.PositiveIntegerField(default=0, verbose_name='عدد التبديلات المنجزة'),
        ),
    ]
