# Generated by Django 6.0.7 on 2026-08-29 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy', '0010_usersquad_is_saved_usersquad_transfers_made'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameweek',
            name='is_finished',
            field=models.BooleanField(default=False),
        ),
    ]
