# Generated by Django 6.0.7 on 2026-08-29 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy', '0011_gameweek_is_finished'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameweek',
            name='is_published',
            field=models.BooleanField(default=False, verbose_name='تم اعتماد ونشر النقاط'),
        ),
        migrations.AlterField(
            model_name='gameweek',
            name='is_finished',
            field=models.BooleanField(default=False, verbose_name='مغلقة/منتهية'),
        ),
    ]
