# Generated by Django 6.0.7 on 2026-08-30 12:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy', '0012_gameweek_is_published_alter_gameweek_is_finished'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='playergameweekstat',
            name='played',
            field=models.BooleanField(default=False, verbose_name='شارك في المباراة'),
        ),
        migrations.AlterField(
            model_name='gameweek',
            name='league',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fantasy.league', verbose_name='الدوري'),
        ),
        migrations.AlterField(
            model_name='player',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='fantasy.realteam', verbose_name='الفريق'),
        ),
        migrations.AlterField(
            model_name='playergameweekstat',
            name='gameweek',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fantasy.gameweek', verbose_name='الجولة'),
        ),
        migrations.AlterField(
            model_name='playergameweekstat',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gameweek_stats', to='fantasy.player', verbose_name='اللاعب'),
        ),
        migrations.AlterField(
            model_name='realteam',
            name='league',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='fantasy.league', verbose_name='الدوري'),
        ),
        migrations.AlterField(
            model_name='userfantasyteam',
            name='league',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_teams', to='fantasy.league', verbose_name='الدوري'),
        ),
        migrations.AlterField(
            model_name='userfantasyteam',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fantasy_teams', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='الصورة الشخصية'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم'),
        ),
        migrations.AlterField(
            model_name='usersquad',
            name='captain',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='captained_in', to='fantasy.player', verbose_name='الكابتن (x2)'),
        ),
        migrations.AlterField(
            model_name='usersquad',
            name='gameweek',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fantasy.gameweek', verbose_name='الجولة'),
        ),
        migrations.AlterField(
            model_name='usersquad',
            name='substitutes',
            field=models.ManyToManyField(blank=True, related_name='subs', to='fantasy.player', verbose_name='الاحتياط (4)'),
        ),
        migrations.AlterField(
            model_name='usersquad',
            name='user_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='squads', to='fantasy.userfantasyteam', verbose_name='فريق المستخدم'),
        ),
        migrations.AlterField(
            model_name='usersquad',
            name='vice_captain',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vice_captained_in', to='fantasy.player', verbose_name='نائب الكابتن'),
        ),
        migrations.AlterUniqueTogether(
            name='gameweek',
            unique_together={('league', 'number')},
        ),
        migrations.AlterUniqueTogether(
            name='playergameweekstat',
            unique_together={('player', 'gameweek')},
        ),
    ]
