# Generated by Django 6.0.7 on 2026-08-30 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy', '0013_playergameweekstat_played_alter_gameweek_league_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='has_red_card',
            field=models.BooleanField(default=False, verbose_name='حاصل على كارت أحمر / طرد'),
        ),
        migrations.AddField(
            model_name='player',
            name='has_yellow_card',
            field=models.BooleanField(default=False, verbose_name='يوجد إنذار سابق (أصفر)'),
        ),
        migrations.AlterField(
            model_name='playergameweekstat',
            name='red_cards',
            field=models.PositiveIntegerField(default=0, verbose_name='كروت حمراء في الجولة'),
        ),
        migrations.AlterField(
            model_name='playergameweekstat',
            name='yellow_cards',
            field=models.PositiveIntegerField(default=0, verbose_name='كروت صفراء في الجولة'),
        ),
    ]
