# Generated by Django 6.0.7 on 2026-08-30 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy', '0014_player_has_red_card_player_has_yellow_card_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playergameweekstat',
            name='red_cards',
        ),
        migrations.RemoveField(
            model_name='playergameweekstat',
            name='yellow_cards',
        ),
        migrations.AddField(
            model_name='playergameweekstat',
            name='red_card',
            field=models.BooleanField(default=False, verbose_name='كارت أحمر للجولة'),
        ),
        migrations.AddField(
            model_name='playergameweekstat',
            name='yellow_card',
            field=models.BooleanField(default=False, verbose_name='كارت أصفر للجولة'),
        ),
    ]
