# Generated by Django 6.0.7 on 2026-08-30 17:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy', '0015_remove_playergameweekstat_red_cards_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='playergameweekstat',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fantasy.realteam', verbose_name='الفريق'),
        ),
    ]
