# Generated by Django 6.0.7 on 2026-09-03 11:37

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy', '0018_alter_realteam_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realteam',
            name='logo',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
