# Generated by Django 6.0.7 on 2026-09-04 22:58

import cloudinary.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy', '0019_alter_realteam_logo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playergameweekstat',
            name='penalties_taken',
        ),
        migrations.AddField(
            model_name='gameweek',
            name='deadline',
            field=models.DateTimeField(blank=True, null=True, verbose_name='موعد إغلاق التشكيلة (Deadline)'),
        ),
        migrations.AddField(
            model_name='player',
            name='chance_of_playing',
            field=models.PositiveIntegerField(default=100, verbose_name='نسبة احتمالية المشاركة %'),
        ),
        migrations.AddField(
            model_name='player',
            name='injury_news',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='تفاصيل الإصابة'),
        ),
        migrations.AddField(
            model_name='player',
            name='is_injured',
            field=models.BooleanField(default=False, verbose_name='مصاب / مشكوك بمشاركته'),
        ),
        migrations.AddField(
            model_name='player',
            name='photo',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='صورة اللاعب'),
        ),
        migrations.AddField(
            model_name='playergameweekstat',
            name='own_goals',
            field=models.PositiveIntegerField(default=0, verbose_name='أهداف عكسية مرماها (-2)'),
        ),
        migrations.AddField(
            model_name='playergameweekstat',
            name='penalties_saved',
            field=models.PositiveIntegerField(default=0, verbose_name='ضربات جزاء تصدى لها الحارس (+5)'),
        ),
        migrations.AddField(
            model_name='userfantasyteam',
            name='bench_boost_used',
            field=models.BooleanField(default=False, verbose_name='تم استخدام Bench Boost'),
        ),
        migrations.AddField(
            model_name='userfantasyteam',
            name='free_hit_used',
            field=models.BooleanField(default=False, verbose_name='تم استخدام Free Hit'),
        ),
        migrations.AddField(
            model_name='userfantasyteam',
            name='triple_captain_used',
            field=models.BooleanField(default=False, verbose_name='تم استخدام Triple Captain'),
        ),
        migrations.AddField(
            model_name='userfantasyteam',
            name='wildcard_used',
            field=models.BooleanField(default=False, verbose_name='تم استخدام Wildcard'),
        ),
        migrations.AddField(
            model_name='usersquad',
            name='active_chip',
            field=models.CharField(choices=[('NONE', 'بدون خاصية'), ('TC', 'Triple Captain (x3)'), ('BB', 'Bench Boost'), ('FH', 'Free Hit'), ('WC', 'Wildcard')], default='NONE', max_length=10, verbose_name='الخاصية المفعّلة'),
        ),
        migrations.AlterField(
            model_name='playergameweekstat',
            name='assists',
            field=models.PositiveIntegerField(default=0, verbose_name='الأسيست (+3)'),
        ),
        migrations.AlterField(
            model_name='playergameweekstat',
            name='penalties_missed',
            field=models.PositiveIntegerField(default=0, verbose_name='ضربات الجزاء الضائعة (-2)'),
        ),
        migrations.AlterField(
            model_name='playergameweekstat',
            name='played',
            field=models.BooleanField(default=False, verbose_name='شارك في المباراة (+2)'),
        ),
        migrations.AlterField(
            model_name='playergameweekstat',
            name='points',
            field=models.IntegerField(default=0, verbose_name='النقاط الإجمالية'),
        ),
        migrations.AlterField(
            model_name='playergameweekstat',
            name='red_card',
            field=models.BooleanField(default=False, verbose_name='كارت أحمر للجولة (-3)'),
        ),
        migrations.AlterField(
            model_name='playergameweekstat',
            name='yellow_card',
            field=models.BooleanField(default=False, verbose_name='كارت أصفر للجولة (-1)'),
        ),
        migrations.AlterField(
            model_name='realteam',
            name='logo',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='شعار الفريق'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='الصورة الشخصية'),
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_date', models.DateTimeField(verbose_name='تاريخ ووقت المباراة')),
                ('is_finished', models.BooleanField(default=False, verbose_name='انتهت المباراة')),
                ('home_score', models.PositiveIntegerField(default=0, verbose_name='أهداف المستضيف')),
                ('away_score', models.PositiveIntegerField(default=0, verbose_name='أهداف الضيف')),
                ('away_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away_matches', to='fantasy.realteam', verbose_name='الفريق الضيف')),
                ('gameweek', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='fantasy.gameweek', verbose_name='الجولة')),
                ('home_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_matches', to='fantasy.realteam', verbose_name='الفريق المستضيف')),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='fantasy.league', verbose_name='الدوري')),
            ],
            options={
                'verbose_name': 'مباراة',
                'verbose_name_plural': 'المباريات',
            },
        ),
        migrations.CreateModel(
            name='NewsAndUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان الخبر')),
                ('content', models.TextField(verbose_name='محتوى الخبر')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ النشر')),
                ('is_pinned', models.BooleanField(default=False, verbose_name='خبر مثبت')),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='news', to='fantasy.league', verbose_name='الدوري')),
            ],
            options={
                'verbose_name': 'خبر / تحديث',
                'verbose_name_plural': 'مركز الأخبار',
                'ordering': ['-is_pinned', '-created_at'],
            },
        ),
    ]
