# Generated by Django 6.0.7 on 2026-09-05 11:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy', '0020_remove_playergameweekstat_penalties_taken_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaguePrize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='عنوان الجائزة')),
                ('prize_type', models.CharField(choices=[('season', 'بطل الموسم'), ('monthly', 'بطل الشهر'), ('gameweek', 'بطل الجولة')], default='season', max_length=20, verbose_name='نوع الجائزة')),
                ('description', models.TextField(verbose_name='وصف الجائزة أو المكافأة')),
                ('icon_emoji', models.CharField(default='🏆', max_length=10, verbose_name='رمز تعبيري (Emoji)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتيب العرض')),
            ],
            options={
                'verbose_name': 'جائزة الدوري',
                'verbose_name_plural': 'جوائز الدوري',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='PlayerStatusUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_reason', models.CharField(max_length=255, verbose_name='سبب الغياب/الشك (مثال: إصابة خلفية، إيقاف كروت)')),
                ('chance_of_playing', models.IntegerField(choices=[(0, 'مستبعد / مصاب (0%)'), (25, 'شكوك عالية (25%)'), (50, 'شكوك متوسطة (50%)'), (75, 'احتمال كبير للمشاركة (75%)'), (100, 'جاهز للعب (100%)')], default=0, verbose_name='احتمالية اللعب')),
                ('news_text', models.TextField(blank=True, null=True, verbose_name='تفاصيل إضافية للخبر')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('is_active', models.BooleanField(default=True, verbose_name='خبر نشط')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_updates', to='fantasy.player', verbose_name='اللاعب')),
            ],
            options={
                'verbose_name': 'تحديث حالة لاعب',
                'verbose_name_plural': 'تحديثات حالات اللاعبين',
            },
        ),
    ]
