# Generated by Django 6.0.7 on 2026-09-05 13:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy', '0021_leagueprize_playerstatusupdate'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Award',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='اسم الجائزة')),
                ('description', models.TextField(blank=True, null=True, verbose_name='وصف الجائزة / المناسبة')),
                ('icon', models.CharField(default='🏆', max_length=50, verbose_name='الإيموجي/الأيقونة')),
                ('date_awarded', models.DateField(auto_now_add=True, verbose_name='تاريخ التتويج')),
                ('winner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='awards', to=settings.AUTH_USER_MODEL, verbose_name='الفائز')),
            ],
            options={
                'verbose_name': 'جائزة / وسام مستخدم',
                'verbose_name_plural': 'جوائز وأوسمة المستخدمين',
                'ordering': ['-date_awarded'],
            },
        ),
    ]
