# Generated by Django 6.0.7 on 2026-09-05 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy', '0022_award'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameweek',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='موعد فتح التشكيلة (الخميس 16:00)'),
        ),
        migrations.AlterField(
            model_name='gameweek',
            name='deadline',
            field=models.DateTimeField(blank=True, null=True, verbose_name='موعد إغلاق التشكيلة (السبت 16:00)'),
        ),
    ]
