# Generated by Django 6.0.7 on 2026-09-06 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy', '0023_gameweek_start_date_alter_gameweek_deadline'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gameweek',
            options={'verbose_name': 'جولة', 'verbose_name_plural': 'الجولات'},
        ),
        migrations.AlterModelOptions(
            name='league',
            options={'verbose_name': 'بطولة / دوري', 'verbose_name_plural': 'البطولات والدوريات'},
        ),
        migrations.AlterModelOptions(
            name='player',
            options={'verbose_name': 'لاعب', 'verbose_name_plural': 'اللاعبون'},
        ),
        migrations.AlterModelOptions(
            name='playergameweekstat',
            options={'verbose_name': 'إحصائية لاعب لجولة', 'verbose_name_plural': 'إحصائيات اللاعبين للجولات'},
        ),
        migrations.AlterModelOptions(
            name='realteam',
            options={'verbose_name': 'فريق حقيقي', 'verbose_name_plural': 'الفرق الحقيقية'},
        ),
        migrations.AlterModelOptions(
            name='userfantasyteam',
            options={'verbose_name': 'فريق فانتسي للمستخدم', 'verbose_name_plural': 'فرق المستخدمين'},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'ملف شخصي', 'verbose_name_plural': 'الملفات الشخصية'},
        ),
        migrations.AlterModelOptions(
            name='usersquad',
            options={'verbose_name': 'تشكيلة جولة للمستخدم', 'verbose_name_plural': 'تشكيلات الجولات للمستخدمين'},
        ),
        migrations.AlterField(
            model_name='usersquad',
            name='substitutes',
            field=models.ManyToManyField(blank=True, related_name='subs', to='fantasy.player', verbose_name='الاحتياط (2)'),
        ),
    ]
