# Generated by Django 6.0.7 on 2026-09-09 02:17

import cloudinary.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy', '0024_alter_gameweek_options_alter_league_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeagueSponsor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم الراعي')),
                ('logo', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='شعار الراعي')),
                ('website_url', models.URLField(blank=True, null=True, verbose_name='رابط موقع الراعي / صفحة الفيسبوك')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتيب العرض')),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sponsors', to='fantasy.league', verbose_name='البطولة')),
            ],
            options={
                'verbose_name': 'راعي بطولة',
                'verbose_name_plural': 'رعاة البطولات',
                'ordering': ['order', 'id'],
            },
        ),
    ]
