# Generated by Django 6.0.7 on 2026-09-12 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy', '0025_leaguesponsor'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersquad',
            name='substitutions_count',
            field=models.PositiveIntegerField(default=0, verbose_name='عدد حركة تبديلات الدكة'),
        ),
    ]
