# Generated by Django 6.0.7 on 2026-09-20 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy', '0026_usersquad_substitutions_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='stored_assists',
            field=models.PositiveIntegerField(default=0, verbose_name='إجمالي التمريرات الحاسمة المخزنة'),
        ),
        migrations.AddField(
            model_name='player',
            name='stored_clean_sheets',
            field=models.PositiveIntegerField(default=0, verbose_name='إجمالي الشباك النظيفة المخزنة'),
        ),
        migrations.AddField(
            model_name='player',
            name='stored_goals',
            field=models.PositiveIntegerField(default=0, verbose_name='إجمالي الأهداف المخزنة'),
        ),
        migrations.AddField(
            model_name='player',
            name='stored_total_points',
            field=models.IntegerField(default=0, verbose_name='إجمالي النقاط المخزنة'),
        ),
    ]
