# Generated by Django 6.0.7 on 2026-09-20 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy', '0027_player_stored_assists_player_stored_clean_sheets_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='stored_assists',
        ),
        migrations.RemoveField(
            model_name='player',
            name='stored_clean_sheets',
        ),
        migrations.RemoveField(
            model_name='player',
            name='stored_goals',
        ),
        migrations.RemoveField(
            model_name='player',
            name='stored_total_points',
        ),
    ]
