# Generated by Django 6.0.7 on 2026-09-20 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy', '0028_remove_player_stored_assists_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='total_assists_accumulated',
            field=models.PositiveIntegerField(default=0, verbose_name='إجمالي الأسيست المجمع'),
        ),
        migrations.AddField(
            model_name='player',
            name='total_clean_sheets_accumulated',
            field=models.PositiveIntegerField(default=0, verbose_name='إجمالي الكلين شيت المجمع'),
        ),
        migrations.AddField(
            model_name='player',
            name='total_goals_accumulated',
            field=models.PositiveIntegerField(default=0, verbose_name='إجمالي الأهداف المجمعة'),
        ),
        migrations.AddField(
            model_name='player',
            name='total_points_accumulated',
            field=models.IntegerField(default=0, verbose_name='إجمالي النقاط المجمعة'),
        ),
        migrations.AddField(
            model_name='player',
            name='total_red_cards_accumulated',
            field=models.PositiveIntegerField(default=0, verbose_name='إجمالي الكروت الحمراء'),
        ),
        migrations.AddField(
            model_name='player',
            name='total_yellow_cards_accumulated',
            field=models.PositiveIntegerField(default=0, verbose_name='إجمالي الكروت الصفراء'),
        ),
    ]
