# Generated by Django 6.0.7 on 2026-09-21 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy', '0029_player_total_assists_accumulated_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='total_assists_accumulated',
        ),
        migrations.RemoveField(
            model_name='player',
            name='total_clean_sheets_accumulated',
        ),
        migrations.RemoveField(
            model_name='player',
            name='total_goals_accumulated',
        ),
        migrations.RemoveField(
            model_name='player',
            name='total_points_accumulated',
        ),
        migrations.RemoveField(
            model_name='player',
            name='total_red_cards_accumulated',
        ),
        migrations.RemoveField(
            model_name='player',
            name='total_yellow_cards_accumulated',
        ),
    ]
