# Generated by Django 6.0.7 on 2026-09-21 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy', '0032_remove_playergameweekstat_penalties_taken_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='playergameweekstat',
            name='penalties_taken',
            field=models.PositiveIntegerField(default=0, verbose_name='ركلات جزاء مسجلة'),
        ),
        migrations.AlterField(
            model_name='playergameweekstat',
            name='suspension_reason',
            field=models.CharField(choices=[('NONE', 'لا يوجد'), ('YELLOW_CARDS', 'تراكم إنذارات'), ('RED_CARD', 'طرد مباشر / كروت'), ('DISCIPLINARY', 'عقوبة أخلاقية / سلوك'), ('CLUB_DECISION', 'قرار إداري / إيقاف نادٍ')], default='NONE', max_length=20, verbose_name='سبب العقوبة'),
        ),
    ]
