# Generated by Django 6.0.7 on 2026-09-22 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy', '0033_playergameweekstat_penalties_taken_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playergameweekstat',
            name='penalties_taken',
        ),
        migrations.AlterField(
            model_name='playergameweekstat',
            name='suspension_reason',
            field=models.CharField(choices=[('NONE', 'لا يوجد'), ('RED_CARD', 'طرد مباشر / كروت'), ('DISCIPLINARY', 'عقوبة أخلاقية / سلوك'), ('CLUB_DECISION', 'قرار إداري / إيقاف نادٍ')], default='NONE', max_length=20, verbose_name='سبب العقوبة'),
        ),
    ]
